Q1
--

In [1]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([11,21,31,41])
a3=np.array([1,22,3,42])
print(a1>a2)
print(a1<a2)
print(a1<a3)
print(a1<=a3)
print(a1>=a3)

[False False False False]
[ True  True  True  True]
[False  True False  True]
[ True  True  True  True]
[ True False  True False]


Q2
--

In [2]:
a4=np.zeros([10])
a5=np.ones([10])
a6=np.full([10],5.0)
print(a4)
print(a5)
print(a6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Q3
--

In [3]:
a7=np.array([0,1,45,30,60,90])
print(np.sum(a7))

226


Q4
--

In [4]:
print(np.add(a1,a2))
print(np.subtract(a1,a2))
print(np.multiply(a1,a2))
print(np.divide(a1,a2))

[12 23 34 45]
[-10 -19 -28 -37]
[ 11  42  93 164]
[0.09090909 0.0952381  0.09677419 0.09756098]


Q5
--

In [9]:
from scipy import linalg
a9=np.mat([[5,2], [3,5]])
print(a9)
print(linalg.sinm(a9))
print(linalg.cosm(a9))
print(linalg.tanm(a9))

[[5 2]
 [3 5]]
[[0.73828129 0.14780318]
 [0.22170477 0.73828129]]
[[-0.21839314  0.49965088]
 [ 0.74947631 -0.21839314]]
[[0.83239421 1.22761782]
 [1.84142673 0.83239421]]


In [1]:
import pandas as pd

Q6
--

In [2]:
data1={'USN':pd.Series([123,234,345]),'Name':pd.Series(['sharu','anu','manu']),'gender':pd.Series(['f','f','m'])}

In [3]:
data1


{'USN': 0    123
 1    234
 2    345
 dtype: int64,
 'Name': 0    sharu
 1      anu
 2     manu
 dtype: object,
 'gender': 0    f
 1    f
 2    m
 dtype: object}

In [4]:
df1=pd.DataFrame(data1)

In [5]:
df1

USN   Name gender
0  123  sharu      f
1  234    anu      f
2  345   manu      m

Q7
--

In [6]:
df2=pd.DataFrame(data1,columns=['Name','score'])

In [7]:
df2

Name score
0  sharu   NaN
1    anu   NaN
2   manu   NaN

Q8
--

In [8]:
import os

In [9]:
os.chdir(r'C:\Users\sharu\OneDrive\Desktop\AIML\Notebook\practice\ml-20m')

In [10]:
movies=pd.read_csv('movies.csv')

In [11]:
movies


movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
27273   131254        Kein Bund für's Leben (2007)   
27274   131256       Feuer, Eis & Dosenbier (2002)   
27275   131258                  The Pirates (2014)   
27276   131260                 Rentun Ruusu (2001)   
27277   131262                    Innocence (2014)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
27273                                       Comedy  
27274                                       Comedy  
27275                                    Adventure  
27276                           (no genres listed)  
27277                     Adventure|Fantasy|Horror  

[27278 rows x 3 columns]

In [36]:
rating=pd.read_csv('ratings1.csv')

In [37]:
rating

userId  movieId  rating   timestamp
0          1        2     3.5  1112486027
1          1       29     3.5  1112484676
2          1       32     3.5  1112484819
3          1       47     3.5  1112484727
4          1       50     3.5  1112484580
...      ...      ...     ...         ...
1056      11     1270     5.0  1230785922
1057      11     1274     5.0  1230784185
1058      11     1291     4.5  1230859001
1059      11     1320     5.0  1230784317
1060      11     1321     4.0  1230784904

[1061 rows x 4 columns]

In [38]:
join1=pd.merge(movies,rating,how='inner',on='movieId')

In [39]:
join1

movieId                       title  \
0           1            Toy Story (1995)   
1           1            Toy Story (1995)   
2           1            Toy Story (1995)   
3           1            Toy Story (1995)   
4           1            Toy Story (1995)   
...       ...                         ...   
1056     8507               Freaks (1932)   
1057     8636         Spider-Man 2 (2004)   
1058     8690  Slaughterhouse-Five (1972)   
1059     8961     Incredibles, The (2004)   
1060    31696          Constantine (2005)   

                                           genres  userId  rating   timestamp  
0     Adventure|Animation|Children|Comedy|Fantasy       3     4.0   944919407  
1     Adventure|Animation|Children|Comedy|Fantasy       6     5.0   858275452  
2     Adventure|Animation|Children|Comedy|Fantasy       8     4.0   833981871  
3     Adventure|Animation|Children|Comedy|Fantasy      10     4.0   943497887  
4     Adventure|Animation|Children|Comedy|Fantasy      11     4.5  1230858821  
...                                           ...     ...     ...         ...  
1056                           Crime|Drama|Horror       1     5.0  1094786027  
1057                 Action|Adventure|Sci-Fi|IMAX       1     4.5  1112485493  
1058                      Comedy|Drama|Sci-Fi|War       1     3.5  1112484795  
1059   Action|Adventure|Animation|Children|Comedy       1     4.0  1112485629  
1060               Action|Fantasy|Horror|Thriller       1     4.0  1112485748  

[1061 rows x 6 columns]

Q9
--

In [21]:
movies.isnull().any()

movieId    False
title      False
genres     False
dtype: bool

Q10
--

In [22]:
data2=pd.Series([100, 200, 300, 400, 500], [1,2,3,4,500])

In [23]:
data2

1      100
2      200
3      300
4      400
500    500
dtype: int64