Q1
--

In [1]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([11,21,31,41])
a3=np.array([1,22,3,42])
print(a1>a2)
print(a1<a2)
print(a1<a3)
print(a1<=a3)
print(a1>=a3)

[False False False False]
[ True  True  True  True]
[False  True False  True]
[ True  True  True  True]
[ True False  True False]


Q2
--

In [2]:
a4=np.zeros([10])
a5=np.ones([10])
a6=np.full([10],5.0)
print(a4)
print(a5)
print(a6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Q3
--

In [3]:
a7=np.array([0,1,45,30,60,90])
print(np.sum(a7))

226


Q4
--

In [4]:
print(np.add(a1,a2))
print(np.subtract(a1,a2))
print(np.multiply(a1,a2))
print(np.divide(a1,a2))

[12 23 34 45]
[-10 -19 -28 -37]
[ 11  42  93 164]
[0.09090909 0.0952381  0.09677419 0.09756098]


Q5
--

In [9]:
from scipy import linalg
a9=np.mat([[5,2], [3,5]])
print(a9)
print(linalg.sinm(a9))
print(linalg.cosm(a9))
print(linalg.tanm(a9))

[[5 2]
 [3 5]]
[[0.73828129 0.14780318]
 [0.22170477 0.73828129]]
[[-0.21839314  0.49965088]
 [ 0.74947631 -0.21839314]]
[[0.83239421 1.22761782]
 [1.84142673 0.83239421]]
